name              'tomcat'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs Apache Tomcat and manages the service'
source_url        'https://github.com/sous-chefs/tomcat'
issues_url        'https://github.com/sous-chefs/tomcat/issues'
chef_version      '>= 15.3'
version           '5.0.11'

supports 'ubuntu'
supports 'debian'
supports 'redhat'
supports 'centos'
supports 'suse'
supports 'opensuseleap'
supports 'scientific'
supports 'oracle'
supports 'amazon'
supports 'zlinux'
