# frozen_string_literal: true

name              'tomcat'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides resources for installing Apache Tomcat and managing systemd services'
source_url        'https://github.com/sous-chefs/tomcat'
issues_url        'https://github.com/sous-chefs/tomcat/issues'
chef_version      '>= 15.3'
version           '6.0.0'

supports 'almalinux', '>= 8.0'
supports 'amazon', '>= 2023.0'
supports 'centos_stream', '>= 9.0'
supports 'debian', '>= 12.0'
supports 'fedora'
supports 'opensuseleap', '>= 16.0'
supports 'oracle', '>= 8.0'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'ubuntu', '>= 22.04'
