#
# Cookbook Name:: tomcat
# Attributes:: default
#
# Copyright 2010, Opscode, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

default["tomcat"]["base_version"] = 6
default["tomcat"]["port"] = 8080
default["tomcat"]["proxy_port"] = nil
default["tomcat"]["ssl_port"] = 8443
default["tomcat"]["ssl_proxy_port"] = nil
default["tomcat"]["ajp_port"] = 8009
default["tomcat"]["catalina_options"] = ""
default["tomcat"]["java_options"] = "-Xmx128M -Djava.awt.headless=true"
default["tomcat"]["use_security_manager"] = false
default["tomcat"]["authbind"] = "no"
default["tomcat"]["deploy_manager_apps"] = true
default["tomcat"]["ssl_cert_file"] = nil
default["tomcat"]["ssl_key_file"] = nil
default["tomcat"]["ssl_chain_files"] = [ ]
default["tomcat"]["keystore_file"] = "keystore.jks"
default["tomcat"]["keystore_type"] = "jks"
# The keystore and truststore passwords will be generated by the
# openssl cookbook's secure_password method in the recipe if they are
# not otherwise set. Do not hardcode passwords in the cookbook.
#default["tomcat"]["keystore_password"] = nil
#default["tomcat"]["truststore_password"] = nil
default["tomcat"]["truststore_file"] = nil
default["tomcat"]["truststore_type"] = "jks"
default["tomcat"]["certificate_dn"] = "cn=localhost"
default["tomcat"]["loglevel"] = "INFO"
default["tomcat"]["tomcat_auth"] = "true"
